UWB-ACM/CTCI

Spring-2019/arrays_sorting/SOLUTIONS_2019Spring.md
Spring-2019/arrays_sorting/zero_matrix/ZeroMatrix.java

Because special handling of the entire first row & column is required (not just `arr[0][0]`), the solution needed to be updated to reflect the correction.

Correction: spring 19 arrays problem 3

---

Spring-2019/linked_lists/SOLUTIONS_2019Spring.md
Spring-2019/linked_lists/rotate_list/rotate_list.cpp
Spring-2019/linked_lists/rotate_list/rotate_list_template.cpp

Solution is implemented in C++. Could use some more tests?
Fixes #11

added Rotate List problem for CTCI LL session

---

Spring-2019/stacks_queues/SOLUTIONS_2019Spring.md
Spring-2019/stacks_queues/validate_stack_sequences/Driver.java

add write-up for problem 3

---

.github/ISSUE_TEMPLATE/template--add-presenters-issue.md
.github/ISSUE_TEMPLATE/template--add-problem.md
.github/ISSUE_TEMPLATE/template--add-reviewers-issue.md

No rush on this one - it would be nice to have these in place for the next academic year.

Created issue templates for future use

---

Spring-2019/system_design_misc_coding/SOLUTIONS_2019Spring.md

Basically consists of advice for approaching the problem in the context of the workshop; most technology-specific content from the chapter has been omitted for brevity and simplicity.

background info section for System Design

---

Spring-2019/trees_graphs/Problem2_UniqueBTS/UniqueBTS.java
Spring-2019/trees_graphs/SOLUTIONS_2019Spring.md

Add tree problem 2: generate valid BST combinations for 1...n

---

2019-03-Autumn/0_arrays_sorting/README.md
2019-03-Autumn/0_arrays_sorting/subsort/Subsort.java

Add subsorting problem for arrays session

---

2019-03-Autumn/0_arrays_sorting/README.md
2019-03-Autumn/0_arrays_sorting/min-group1s/min-group1s.py

Add min-group1s problem for arrays session

---

2019-03-Autumn/0_arrays_sorting/README.md
2019-03-Autumn/0_arrays_sorting/TwoSumTest/Driver.java

Re-creating the PR because it disappeared.
Closes #86 when merged.

Problem 1: Two Sum

---

2019-03-Autumn/1_linked_lists/README.md
2019-03-Autumn/1_linked_lists/sum_lists/sumlists.cpp
2019-03-Autumn/1_linked_lists/sum_lists/sumlists_inorder.cpp

Add solution for CTCI 2.5 for linked list session

---

2019-03-Autumn/1_linked_lists/README.md
2019-03-Autumn/1_linked_lists/loop_detection/loop_detection.cpp

Add loop detection problem for linked list session

---

2019-03-Autumn/1_linked_lists/README.md
2019-03-Autumn/1_linked_lists/kth_to_last/driver.py
2019-03-Autumn/1_linked_lists/kth_to_last/solutions.py
2019-03-Autumn/1_linked_lists/kth_to_last/utils.py

Add CTCI 2.2 (Kth to Last) for Linked List session

---

2019-03-Autumn/2_string_manipulation/README.md
2019-03-Autumn/2_string_manipulation/custom_sort_string/custom_sort_string.cpp

Add custom sort string problem for string manipulation session

---

2019-03-Autumn/2_string_manipulation/README.md
2019-03-Autumn/2_string_manipulation/longest_substring/driver.py
2019-03-Autumn/2_string_manipulation/longest_substring/solution.py

Add solution for Longest Common Substring problem

---

README.md

Includes:
* Question banks
* Interview study guides
* Mock interview practice resources & sites
* Resume help
Needs:
Closes #93

Add resources for job hunting & interview prep

---

2019-03-Autumn/3_stacks_queues/README.md
2019-03-Autumn/3_stacks_queues/backspace_string_compare/backspace_string_compare.py

Add backspace string compare problem for stack+queues session

---

2019-03-Autumn/3_stacks_queues/README.md
2019-03-Autumn/3_stacks_queues/reverse_substrings/reverse.cpp

Closes #69
Unfortunately, paragraphs are causing the diffs to be rendered in an illogical way; rebasing the branch(es) after PRs are applied should fix this.

Provide writeup for Problem 3 (Stacks + Queues)

---

2019-03-Autumn/4_trees/README.md
2019-03-Autumn/4_trees/height/driver.py
2019-03-Autumn/4_trees/height/solution.py

Add problem 1 for trees session (fall 2019)

---

2019-03-Autumn/5_graphs/README.md
2019-03-Autumn/5_graphs/boggle/driver.py
2019-03-Autumn/5_graphs/boggle/solution.py

Add problem and solution for Graphs Q3 (fall 2019)

---

2019-03-Autumn/5_graphs/README.md

Add session title for graphs (fall 2019)

---

2019-03-Autumn/6_dyn_prog/README.md
2019-03-Autumn/6_dyn_prog/stairs/driver.py
2019-03-Autumn/6_dyn_prog/stairs/solution.py

Add problem and code for dynprog Q1 (fall 2019)

---

2019-03-Autumn/6_dyn_prog/README.md
2019-03-Autumn/6_dyn_prog/word_break/word_break.py

Add word break problem for dynprog session

---

2019-03-Autumn/7_mock_interviews/2.md
2019-03-Autumn/7_mock_interviews/diving_board_solution/driver.java

Committing solution for technical diving board problem

Diving-board-solution

---

2020-01-Winter/0_arrays_sorting/README.md
2020-01-Winter/0_arrays_sorting/spiral/driver.py
2020-01-Winter/0_arrays_sorting/spiral/solution.py

Add problem 3 (spiral matrix) for arrays & sorting session

---

2020-01-Winter/0_arrays_sorting/README.md
2020-01-Winter/0_arrays_sorting/search_in_rotated/solution.cpp

GitHub desktop errors so doing a manual push with the changes to the readme

Manual Push

---

2020-01-Winter/1_linked_lists/Flatten_Multilevel_Doubly_Linked_List/LinkedList.java
2020-01-Winter/1_linked_lists/README.md

The implementation of flatten is correct but a little shaky on general driver implementation to show how it works. Also needed some time to get used to using GitHub.

Multilevel doubly linked list

---

2020-01-Winter/2_string_manipulation/README.md
2020-01-Winter/2_string_manipulation/validate_IP/validate_IP.py

adding string manipulation question 1 - validate IP address - problem and solution
1 remaining TODO outside any requested revisions: add github link to validate_IP.py file in readme

adding validateIP string manip solution

---

2020-01-Winter/2_string_manipulation/README.md
2020-01-Winter/2_string_manipulation/minimum_window/driver.py
2020-01-Winter/2_string_manipulation/minimum_window/solution.py

Add minimum substring window problem

---

2020-01-Winter/3_stacks_queues/README.md

I will upload my python file now that I understand what I did wrong and sorry about the inconvenience.

Adding my problem description and solution for the README file

---

2020-01-Winter/3_stacks_queues/README.md
2020-01-Winter/3_stacks_queues/TrappingRainWater/TrappingRainWater.py

Made changes for stack and queue

Adding Stack and queue changes

---

2020-01-Winter/3_stacks_queues/ValidParentheses
2020-01-Winter/3_stacks_queues/valid_parentheses/ValidParentheses.cpp

Using c++ and the stack standard library

ValidParenthses.cpp

---

2020-01-Winter/3_stacks_queues/README.md

Revert "Update README.md"

---

2020-01-Winter/4_trees/README.md
2020-01-Winter/4_trees/serialize-and-deserialize-a-tree/serialize-and-deserialize-a-tree.java

Added problem statement and solution in Java. Verified by submitting the solution to leetcode.com

Added serialization and desalinization of binary tree problem - Fixes #138

---

2020-01-Winter/5_graphs/Bipartite/Bipartite_Solution.java
2020-01-Winter/5_graphs/README.md

Problem 3: is it bipartite, the solution is included.
Actions related to this request:
updated writeup
updated readme.md
added solution in Java
Thank you for your review and please let me know if you have any questions.
-- Bill

Add graph problem 3 to CTCI 02/21/2020

---

2020-02-Spring/0_arrays_matrix/README.md
2020-02-Spring/1_strings/README.md
2020-02-Spring/2_linked_lists/README.md
2020-02-Spring/3_trees/README.md
2020-02-Spring/4_graphs/README.md
2020-02-Spring/5_behavioral_interviews/README.md
2020-02-Spring/6_dynamic_programming/README.md
2020-02-Spring/8_bring_your_questions/README.md

added spring 2020 folder and subfolders

---

2020-02-Spring/0_arrays_matrix/README.md

Updated topic title

---

2020-02-Spring/0_arrays_matrix/README.md
2020-02-Spring/0_arrays_matrix/buy_stock/driver.java
2020-02-Spring/0_arrays_matrix/buy_stock/solution.java

Just the question, I will create a PR for the driver later.
Update: updated, in final stage.

Question 1

---

2020-02-Spring/2_linked_lists/README.md

1. Updated title and description.
2. Added drop-downs for all solutions for consistency.

Changing structure for consistency

---

2020-03-Autumn/1_pointer_techniques/QuestionOne/driver.cpp
2020-03-Autumn/1_pointer_techniques/README.md

Added the first question for the upcoming CTCI 'Merge Sorted Arrays '

Question One added 'Remove Duplicates' AFC

---

2020-03-Autumn/1_pointer_techniques/README.md

Did the C++ and Java solution for Linked List Contains Cycle. More familiar with java so my explanations are for the java solutions.

Implemented Problem 2 with Solution

---

2020-03-Autumn/2_modified_binary_search/README.md

Question one 'Sqrtx' done

---

2020-03-Autumn/4_intervals/QuestionOne/driver.cpp
2020-03-Autumn/4_intervals/README.md

A solution to Leetcode question 57 Insert Intervals

Solve Leetcode question #57 Insert Intervals

---

2021-01-Winter/3_graph_traversal/README.md
2021-01-Winter/3_graph_traversal/sametree/SameTree.cpp

Updated README.md with problem and solution for SameTree.
Included SameTree.cpp with solution code and test cases.

Initial Commit for new question SameTree.
